#!/bin/sh -e


#this script runs once at the installation. place your code below
echo "You are installing the app"

# ensure the conf directory exists
if [ ! -f "$SNAP_COMMON/script.sh" ]; then
	cp -a $SNAP/bin/script.sh  $SNAP_COMMON/script.sh
	touch $SNAP_COMMON/autostarton
	exit 0
fi





